config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trackers
  # get 'home/index'
  get 'home/about'
  root 'home#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tracker.rb
class Tracker < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :set_tracker, only: %i[ show edit update destroy ]

  # GET /trackers or /trackers.json
  def index
    @trackers = Tracker.all
  end

  # GET /trackers/1 or /trackers/1.json
  def show
  end

  # GET /trackers/new
  def new
    @tracker = Tracker.new
  end

  # GET /trackers/1/edit
  def edit
  end

  # POST /trackers or /trackers.json
  def create
    @tracker = Tracker.new(tracker_params)

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to tracker_url(@tracker), notice: "Tracker was successfully created." }
        format.json { render :show, status: :created, location: @tracker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1 or /trackers/1.json
  def update
    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to tracker_url(@tracker), notice: "Tracker was successfully updated." }
        format.json { render :show, status: :ok, location: @tracker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1 or /trackers/1.json
  def destroy
    @tracker.destroy

    respond_to do |format|
      format.html { redirect_to trackers_url, notice: "Tracker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      @tracker = Tracker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tracker_params
      params.require(:tracker).permit(:course, :assignment, :center, :weight, :due_date, :start_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Assin Tracker', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      <% if !user_signed_in? %>
      <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Log In',  new_user_session_path, class:"nav-link" %>
        </li>
      <%end%>
       
        <li class="nav-item">
        <%= link_to 'Assignments', trackers_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Add Course', new_tracker_path, class:"nav-link" %>
        </li>
        <li class="nav-item">

        <% if user_signed_in? %>

        <li class="nav-item">
        <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign Out',  destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <%end%>

        <li class="nav-item">
        <%= link_to 'Tracker', home_about_path, class:"nav-link text-warning" %>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container bg-secondary">
<h1 class="display-1">About Us</h1>
<h1 class="text-warning">Assin Tracking</h1>
<p class="text-white">An Assingment Tracking App</p>
</div>

app/views/home/index.html.erb
<div class="container bg-secondary">
<h1 class="text-warning">Assin Tracking</h1>
<p class="text-white">An Assingment Tracking App</p>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%=notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Rails App One</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'home/header'%>
 <div class="contianer">
 <%if notice %>
  <%= render 'layouts/alerts' %>
 <% end %>

  <%= yield %>
  
  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/trackers/_form.html.erb
<%= form_with(model: tracker) do |form| %>
  <% if tracker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tracker.errors.count, "error") %> prohibited this tracker from being saved:</h2>

      <ul>
        <% tracker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="card text-white bg-dark" style="width: 18rem;"> 
  <div class="card-title">
  <div class="field form-group" >
    <% form.label :course, class:'form-label' %>
    <%= form.text_field :course, class:'form-control', placeholder:"Course" %>
  </div>

  <div class="field form-group">
    <% form.label :assignment, class:'form-label' %>
    <%= form.text_field :assignment, class:'form-control', placeholder:"Assignment" %>
  </div>

  <div class="field form-group">
    <% form.label :center, class:'form-label' %>
    <%= form.text_field :center, class:'form-control', placeholder:"Center" %>
  </div>

  <div class="field form-group">
    <% form.label :weight, class:'form-label' %>
    <%= form.text_field :weight, class:'form-control', placeholder:"Weight" %>
  </div>

  <div class="field form-group">
    <%= form.label :due_date, class:'form-label' %>
    <%= form.date_select :due_date, class:'form-control', placeholder:"Date Due" %>
  </div>

  <div class="field form-group">
    <%= form.label :start_date, class:'form-label' %>
    <%= form.date_select :start_date, class:'form-control', placeholder:"Date Started" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
  </div>
<% end %>

app/views/trackers/edit.html.erb
<h3 class="card-header text-white bg-dark" style="width: 18rem">Edit</h3>

<%= render 'form', tracker: @tracker %>

<%= link_to 'Show', @tracker %> |
<%= link_to 'Back', trackers_path %>

app/views/trackers/index.html.erb
<table class="table table-dark table-striped table-hover table-bordered border-white">

  <thead>
  <h4 class="table-text bg-secondary mb-0 text-warning">Tracking</h4>
    <tr>
      <th>Course</th>
      <th>Assignment</th>
      <th>Center</th>
      <th>Weight</th>
      <th>Due date</th>
      <th>Start date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trackers.each do |tracker| %>
      <tr>
        <td><%= tracker.course %></td>
        <td><%= tracker.assignment %></td>
        <td><%= tracker.center %></td>
        <td><%= tracker.weight %></td>
        <td><%= tracker.due_date %></td>
        <td><%= tracker.start_date %></td>
        <td><%= link_to 'Show', tracker %></td>
        <td><%= link_to 'Edit', edit_tracker_path(tracker) %></td>
        <td><%= link_to 'Delete', tracker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Tracker', new_tracker_path %>

app/views/trackers/new.html.erb
<h3 class="card-header text-white bg-dark" style="width: 18rem">New Tracker</h3>

<%= render 'form', tracker: @tracker %>

<%= link_to 'Back', trackers_path %>

app/views/trackers/show.html.erb
<div class="card bg-dark text-white mt-3" style="width: 18rem;">
  <div class="card-body">

    <h5 class="card-title text-warning">
      <strong>Assignment:</strong>
      <%= @tracker.assignment %>
    </h5>

    <h6 class="card-subtitle mb-3">
  <strong>Course:</strong>
  <%= @tracker.course %>
</h6>
<hr/>


<p class="card-text">
  <strong>Center:</strong>
  <%= @tracker.center %>
</p>

<p class="card-text">
  <strong>Weight:</strong>
  <%= @tracker.weight %>
</p>

<p class="card-text text-success">
  <strong>Due date:</strong>
  <%= @tracker.due_date %>
</p>

<p class="card-text">
  <strong>Start date:</strong>
  <%= @tracker.start_date %>
</p>

<%= link_to 'Edit', edit_tracker_path(@tracker), class:"btn btn-dark" %> 
<%= link_to 'Back', trackers_path, class:"btn btn-dark" %>

  </div>
</div>